### ISSUE TITLE
Requires reboot after running script

### ISSUE THREAD

**Issue by adambutler** [FluffyJack/node-rolling-spider#1]
First of all thanks for working on this... great job :+1: I will be using it in a @nodeschool talk this Saturday.

I've noticed that you seem to need to remove the battery after each successful connection, are you able to close the connection so that it may be reopened again?

**Comment by iamphill** [comment]
noble has a disconnect method in it https://www.npmjs.com/package/noble#disconnect-or-cancel-pending-connection so would be straightforward to add :+1: 

I guess until then you could do the following? (Not tested though)

```javascript
yourDrone.ble.disconnect();
```

**Comment by voodootikigod** [comment]
This has been fixed. Use version 1.0.0
