### ISSUE TITLE
Windows Support ?!

### ISSUE THREAD

**Issue by moszeed** [FluffyJack/node-rolling-spider#27]
Hi i cant join the fun to fly my Rolling-Spider with Node,
because i can`t install this module on my Windows 8 or 10 Machine.
Following message appears:
```
λ npm install rolling-spider
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules \\npm\\bin\\npm-cli.js" "install" "rolling-spider"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: rolling-spider@1.1.2
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```
Thanks in advance

**Comment by ChrisTheBaron** [comment]
Hey, 

This is because the Bluetooth module it depends on only runs on Linux and iOS at the moment, sorry :) 

Cheers, Chris

**Comment by blhack** [comment]
I think ChrisTheBaron means Linux and OSX, right?  (This does run on OSX [yosemite, at least.  Having trouble with mavericks right now]).

**Comment by ChrisTheBaron** [comment]
Hey, 

Yes that is what I meant, thank you :) 

Cheers, Chris

**Comment by moszeed** [comment]
hm, thats sad :(

**Comment by voodootikigod** [comment]
Yes it is sad I am trying to work with @microsoft to get their ble Apis not
to be a nightmare

On Monday, June 1, 2015, Moszeed <notifications@github.com> wrote:

> hm, thats sad :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FluffyJack/node-rolling-spider/issues/27#issuecomment-107322346>
> .
>


-- 
*Chris Williams*

@voodootikigod <http://twitter.com/voodootikigod> | GitHub
<http://github.com/voodootikigod>

*Maker of Improbable Things:* JSConf <http://jsconf.com/> | RobotsConf
<http://robotsconf.com/> | Beer.js <http://beerjs.com> | Logo.js
<https://github.com/voodootikigod/logo.js> | node-serialport
<http://nodebots.io/>

**Comment by voodootikigod** [comment]
@blhack can you provide logs from mavericks?

**Comment by sandeepmistry** [comment]
@voodootikigod apologies for going off topics ...

@blhack's going to try a patch out for me. It looks like OS X 10.9 stopped emitting an event for write without response requests, so the write callback is never called, and things get stuck. If all goes well the latest noble will have a fix for this.

**Comment by voodootikigod** [comment]
Closing as the root issue is with Noble and windows support (which has a ticket already).
