### ISSUE TITLE
Cannot connect to my minidrone

### ISSUE THREAD

**Issue by murariuroger** [FluffyJack/node-rolling-spider#3]
Hi,
  I tried to connect to my rolling spider. I'm new with nodejs, maybe I did something wrong. I ran from terminal 'sudo node discover.js' but nothing happend. Running this should print on terminal the drone nearby my laptop, right? I have installed on my laptop ubuntu 14.04, linux version 3.16

**Comment by voodootikigod** [comment]
are you sure you had Bluetooth enabled and Bluetooth 4.0 compatible chipset?

**Comment by voodootikigod** [comment]
Also make sure no other phone/device that has connected to it before still has a bluetooth lock on it.

**Comment by voodootikigod** [comment]
Closing due to lack of information.
