### ISSUE TITLE
takeOff never completes

### ISSUE THREAD

**Issue by johndemic** [FluffyJack/node-rolling-spider#4]
Calling yourDrone.takeOff() never seems to complete or invoke its callback.  My drone does take off, hovering a couple of feet off the floor, and stays there as the script hangs.

**Comment by petershaw** [comment]
Hi. DId you find a solution? Same problem here. Maybe we can figure this out together?

**Comment by voodootikigod** [comment]
What firmware version are you on?

**Comment by voodootikigod** [comment]
Closing try version 1.0.0 please.
