### ISSUE TITLE
Bring together all the tribes!!!

### ISSUE THREAD

**Issue by voodootikigod** [FluffyJack/node-rolling-spider#6]
One node rolling spider for all, we should actively integrate/merge down/combine the great work done by @ChrisTheBaron and @DroneWorks into a single node-rolling-spider repository. @FluffyJack it would be worthwhile adding contributors so we can help with this effort, if you so deem it appropriate.

**Comment by rwaldron** [comment]
I wasn't cc'ed, but I fully endorse this proposal and offer my services as a device tester (I own both the rolling spider and jumping sumo)

**Comment by voodootikigod** [comment]
This has been done. Version 1.0.0 has been published! yay.
